name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6
    - name: Run tests
      run: |
        sudo chmod -R 777 vendor/pestphp/pest/.temp
        vendor/bin/pest

